# -*- coding: utf-8 -*-

WEEK1 = {
    'week_line': '1 — Introduction to HTML & Web Development (Aug 31)',
    'lessons': [
        {
            'title': 'Essential Agreement & Year/Unit Overview',
            'standard': 'N/A - Course & classroom orientation (content standards begin Lesson 3)',
            'literacy': ['Active listening; structured class discussion; think-pair-share'],
            'assessment': ['Formative - observation of participation;', '"About Me & My Goals" reflection card'],
            'walt': ['To co-create classroom essential agreements and understand the full Design 1', 'year map, so I can make an informed elective choice and know what to', 'expect this term.'],
            'wilf': ["- I can name at least 2 of the 3 terms' focus areas", '- I have helped shape the class essential agreements', '- I know the elective decision timeline'],
            'vocab': ['None new this lesson (course orientation)'],
            'resources': ['Projector/slides (year map + pathway diagram),', 'essential agreement chart, reflection form'],
            'national_identity': ['UAE Digital Transformation and Future Skills - framing', "why digital design skills matter for the UAE's economy"],
            'ai_digital': ["Discuss the school's Academic Integrity Policy on", 'permitted AI tool use, ahead of any coding work'],
            'i_do': ['Teacher introduces the Design 1 year map (3 terms)', 'and the Grade 6-12 course pathway'],
            'we_do': ['Class co-creates essential agreements together;', 'guided discussion on the Design vs Visual Arts choice'],
            'you_do': ['Students individually complete the "About Me &', 'My Goals for This Course" reflection'],
            'diff_beginning': 'Sentence starters for the reflection; paired discussion first',
            'diff_on': 'Complete the reflection independently using the prompts',
            'diff_above': 'Add a goal connecting this course to a future career/interest',
            'closure': ['Write one question you still have about the course', '(sticky note / Toddle comment)'],
            'inclusion': ['Visual Supports', 'Chunked Instructions', 'Scaffold / Sentence Starters'],
            'gt': ['Real-World Application', 'Open-Ended Task'],
        },
        {
            'title': 'Platform & Login Setup',
            'standard': 'N/A - Technical/platform onboarding (content standards begin Lesson 3)',
            'literacy': ['Following sequential written/verbal instructions;', 'technical vocabulary introduction'],
            'assessment': ['Formative - proof of working save location, editor,', 'and Hello World file (screenshot to Toddle)'],
            'walt': ['To successfully log into my laptop and every platform needed for', 'Design 1, so no future lesson is lost to tech troubleshooting.'],
            'wilf': ['- I am logged into my laptop, school network, and Toddle', '- I have a working code editor', '- My Hello World file is saved and opens in a browser'],
            'vocab': ['Code Editor - a program used to write/save code', 'File Extension - the letters after the dot in a filename'],
            'resources': ['School laptops/network, VS Code or Notepad, Toddle,', 'printed step-by-step login checklist'],
            'national_identity': ['UAE Digital Transformation and Future Skills - using the', 'same professional tools UAE tech companies use'],
            'ai_digital': ['Setting up the code editor and LMS platforms used all', 'term; no AI tool use required this lesson'],
            'i_do': ['Teacher demonstrates the full login/setup sequence', 'step by step (laptop, Toddle, editor, folders, Hello World)'],
            'we_do': ['Students follow along at each checkpoint (login,', 'editor install-check, folder setup)'],
            'you_do': ['Students independently create, save, and open their', 'own Hello World file, then submit proof to Toddle'],
            'diff_beginning': 'Printed checklist with screenshots; paired peer buddy',
            'diff_on': 'Follow the checklist independently, teacher spot-checks',
            'diff_above': 'Explore one extra editor feature (theme/extension) if early',
            'closure': ['Show of hands - who has everything working?', 'Log unresolved issues for IT follow-up'],
            'inclusion': ['Chunked Instructions', 'TA/LSA Support', 'Visual Supports'],
            'gt': ['Independent Inquiry', 'Extension / Challenge Task'],
        },
        {
            'title': 'What Is HTML? Exploring the Web Around Us',
            'standard': ['PG 4: Use systems thinking to describe networks and common software', 'and hardware components. (Computing Systems & Networks, GLE', 'CS.HS.2.3 - Computer software is written for specific purposes.)'],
            'literacy': ['Tier 3 vocabulary instruction (Tag, Element, Attribute);', 'comparing two texts (websites); guided note-taking'],
            'assessment': ['Formative - exit ticket written response', '("Explain the role of HTML in web development")'],
            'walt': ['To explain the purpose of HTML and identify the key', 'components of a webpage.'],
            'wilf': ['- I can define HTML in my own words', '- I can identify at least 3 webpage components', '- I can explain why HTML matters for communication'],
            'vocab': ['HTML, Browser, Tag, Element, Attribute, Website,', 'Webpage - see Term 1 Vocabulary list for definitions'],
            'resources': ['Two contrasting real websites, browser View Page', 'Source/Inspect Element, "Website Anatomy" worksheet'],
            'national_identity': ['UAE Digital Transformation and Future Skills - how UAE', 'government/business sites communicate with citizens'],
            'ai_digital': ['Using built-in browser developer tools (View Page', 'Source/Inspect Element) as a digital literacy skill'],
            'i_do': ['Mini-lecture on what HTML is; live demo revealing HTML', 'underneath a real website via View Page Source'],
            'we_do': ['Teacher-led walkthrough identifying webpage components', '(header, nav, content, footer) on a sample site'],
            'you_do': ['In pairs, students browse two sites and complete the', '"Website Anatomy" worksheet'],
            'diff_beginning': 'Pre-taught vocabulary; worksheet with word bank + example',
            'diff_on': 'Complete the worksheet in pairs using new vocabulary',
            'diff_above': 'Explain one extra concept spotted in View Page Source',
            'closure': ['Exit ticket - "Explain the role of HTML in web development"', 'in one sentence'],
            'inclusion': ['Pre-teach Vocabulary', 'Model / Worked Example', 'Visual Supports'],
            'gt': ['Higher-Order Questioning', 'Depth & Complexity Task'],
        },
        {
            'title': 'Building Your First HTML File',
            'standard': ['PG 4: Use systems thinking to describe networks and common software', 'and hardware components. (Computing Systems & Networks, GLE CS.HS.2.3)'],
            'literacy': ['Modeled/shared writing (code as structured text);', 'sequencing steps; self-monitoring while writing'],
            'assessment': ['Formative (official Week 1 checkpoint) - observation,', 'questioning, exit ticket; index.html submitted to Toddle'],
            'walt': ['To create and save a basic HTML file independently,', 'applying correct file-saving conventions.'],
            'wilf': ['- My file is saved correctly as index.html', '- It displays correctly in a browser', '- It contains a title and at least one paragraph'],
            'vocab': ['Syntax - the exact rules for writing code correctly'],
            'resources': ['Code editor, browser, previous Hello World file as a', 'starting reference'],
            'national_identity': ['UAE Digital Transformation and Future Skills - building', 'the first artifact of a professional online presence'],
            'ai_digital': ['Reminder: AI code-generation tools are not permitted for', 'this task per the Academic Integrity Policy'],
            'i_do': ['Teacher demos building a new HTML file with a title', 'and personal-introduction paragraph'],
            'we_do': ['Students follow along step-by-step to build their own', 'basic personal HTML file alongside the teacher'],
            'you_do': ['Students independently save, open in browser,', 'troubleshoot, and submit their file to Toddle'],
            'diff_beginning': 'Sentence starters for the intro paragraph; worked example visible',
            'diff_on': 'Write an original introduction paragraph independently',
            'diff_above': 'Add a second paragraph or heading before submitting',
            'closure': ['Exit ticket - submit index.html to Toddle as this', "week's formal formative check"],
            'inclusion': ['Model / Worked Example', 'Scaffold / Sentence Starters', 'Extra Processing Time'],
            'gt': ['Extension / Challenge Task', 'Open-Ended Task'],
        },
    ],
}

WEEK2 = {
    'week_line': '2 - HTML Document Structure (Sept 7)',
    'lessons': [
        {
            'title': 'The Anatomy of an HTML Document',
            'standard': ['PG 1: Develop, utilize and evaluate algorithms to model and solve', 'problems. (Computational Thinking, GLE CS.HS.1.4 - Large, complex', 'problems can be broken down into smaller, manageable components.)'],
            'literacy': ['Guided note-taking with a labeled diagram; technical', 'vocabulary instruction (Doctype, Head, Body, Nesting)'],
            'assessment': ['Formative - quick write exit ticket', '("What would happen if we left out <body>?")'],
            'walt': ['To explain and correctly use the core structural tags:', '<!DOCTYPE html>, <html>, <head>, <title>, and <body>.'],
            'wilf': ['- I can name the 5 core structural tags in order', '- I can explain the difference between <head> and <body>'],
            'vocab': ['Doctype Declaration, Head, Body, Nesting'],
            'resources': ['Sample HTML document structure diagram, code editor,', 'browser'],
            'national_identity': ['UAE Digital Economy - professional websites need a', 'reliable, standard structure to be trustworthy'],
            'ai_digital': ['None planned this lesson - concept taught through', 'direct teacher demonstration'],
            'i_do': ['Mini-lecture on the standard HTML "skeleton"; live demo', 'building structure line by line, tied to decomposition'],
            'we_do': ['Class diagnoses a "broken" structure example together;', 'guided notes on the labeled structure diagram'],
            'you_do': ['Students label a blank HTML structure diagram', 'independently with tag names and descriptions'],
            'diff_beginning': 'Diagram provided with a word bank of tag names to match',
            'diff_on': 'Label the diagram from memory using notes as backup',
            'diff_above': 'Explain in writing why tag order/nesting matters',
            'closure': ['Quick write - "What would happen if we left out', 'the <body> tag?"'],
            'inclusion': ['Visual Supports', 'Pre-teach Vocabulary', 'Chunked Instructions'],
            'gt': ['Higher-Order Questioning'],
        },
        {
            'title': 'Guided Build: Structuring a Page',
            'standard': ['PG 1: Develop, utilize and evaluate algorithms to model and solve', 'problems. (Computational Thinking, GLE CS.HS.1.4)'],
            'literacy': ['Sequential instruction-following; error analysis', '(spotting syntax mistakes in text)'],
            'assessment': ['Formative - partner structure-checklist review'],
            'walt': ['To build a correctly structured HTML document using html,', 'head, title, and body tags with teacher support.'],
            'wilf': ['- My document includes all 5 core tags, correctly nested', '- My page renders in the browser with no visible errors'],
            'vocab': ['Opening Tag, Closing Tag, Case Sensitivity'],
            'resources': ['Code editor, browser, structure checklist handout'],
            'national_identity': ['UAE Digital Economy'],
            'ai_digital': ['None planned this lesson'],
            'i_do': ['Teacher models building a document structure one step', 'at a time across three checkpoints'],
            'we_do': ['Students replicate each checkpoint with the teacher', '(DOCTYPE+html, head+title, body), then add heading/paragraph'],
            'you_do': ['Students build a new page "shell" independently, then', 'swap with a partner to check structure'],
            'diff_beginning': 'Checkpoints broken into smaller sub-steps with TA check-ins',
            'diff_on': 'Follow the three checkpoints with teacher circulating',
            'diff_above': 'Add an extra nested element beyond the minimum',
            'closure': ['Partner check - swap screens and review using the', 'structure checklist'],
            'inclusion': ['Chunked Instructions', 'TA/LSA Support', 'Model / Worked Example'],
            'gt': ['Extension / Challenge Task'],
        },
        {
            'title': 'Independent Build: Expanding Your Homepage',
            'standard': ['PG 1: Develop, utilize and evaluate algorithms to model and solve', 'problems. (Computational Thinking, GLE CS.HS.1.4)'],
            'literacy': ['Independent expository writing (about-me content);', 'self-editing/proofreading own code'],
            'assessment': ['Informal - teacher circulation check'],
            'walt': ['To apply correct HTML document structure independently to', 'expand my personal website homepage.'],
            'wilf': ['- My file structure is valid and complete', '- My content is organized logically under clear headings'],
            'vocab': ['None new this lesson (applying prior vocabulary)'],
            'resources': ['Code editor, browser, own index.html from previous', 'lessons'],
            'national_identity': ['UAE Digital Economy - building a genuine online presence'],
            'ai_digital': ['Independent build time; AI code generation not permitted', 'per Academic Integrity Policy'],
            'i_do': ['Brief review of the structure checklist from Lesson 2'],
            'we_do': ['N/A this lesson - teacher circulates for 1:1 support', 'rather than whole-class instruction'],
            'you_do': ['Students independently expand their homepage with 2+', 'headings/paragraphs; stretch = start a second file'],
            'diff_beginning': 'Sentence starters for new content; paired support available',
            'diff_on': 'Expand content independently using minimum requirements',
            'diff_above': 'Begin a second properly structured file (e.g. about.html)',
            'closure': ['None formal - informal circulation check by the teacher'],
            'inclusion': ['Scaffold / Sentence Starters', 'Flexible Grouping'],
            'gt': ['Independent Inquiry', 'Student-Led /Passion project'],
        },
        {
            'title': 'Peer Review & Structure Check',
            'standard': ['PG 1: Develop, utilize and evaluate algorithms to model and solve', 'problems. (Computational Thinking, GLE CS.HS.1.4)'],
            'literacy': ['Structured peer feedback protocol; oral explanation', 'of technical work'],
            'assessment': ['Formative (official Week 2 checkpoint) - HTML structure', 'check against success criteria'],
            'walt': ['To review and correct HTML document structure errors', "through peer feedback and complete the week's formal check."],
            'wilf': ['- I create a valid HTML document structure', '- I use tags correctly', '- My content displays successfully in a browser'],
            'vocab': ['None new this lesson (consolidation)'],
            'resources': ['Code editor, browser, structure checklist'],
            'national_identity': ['UAE Digital Economy'],
            'ai_digital': ['None planned this lesson'],
            'i_do': ['Quick-fire whole-class troubleshooting of the 2-3 most', 'common recurring errors observed'],
            'we_do': ['Peer review in pairs using the structure checklist'],
            'you_do': ['Students independently fix issues flagged by their', 'partner and submit the final corrected file'],
            'diff_beginning': 'Paired with a stronger peer for review; TA support for fixes',
            'diff_on': 'Complete peer review and fixes independently',
            'diff_above': 'Support a peer with debugging after finishing own fixes',
            'closure': ["One thing your partner helped you fix today"],
            'inclusion': ['Flexible Grouping', 'TA/LSA Support'],
            'gt': ['Leadership / Peer Coaching'],
        },
    ],
}
